steps:
  - name: "gcr.io/kaniko-project/executor:v1.3.0"
    args:
      - --destination=gcr.io/seqr-dev-385323/seqr:${COMMIT_SHA}
      - --destination=gcr.io/seqr-dev-385323/seqr:${_CUSTOM_BRANCH_TAG}
      - --destination=gcr.io/seqr-dev-385323/seqr:latest
      - --dockerfile=deploy/docker/seqr/Dockerfile
      - --cache=true
      - --cache-ttl=168h

timeout: 1800s
