name: seqr prod release
on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed
    branches:
      - master

permissions:
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: authenticate to google cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{secrets.GCP_KEY}} | base64 -d"

      - name: "setup gcloud sdk"
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push Docker image - api
        uses: docker/build-push-action@v3
        with:
          file: deploy/docker/seqr/Dockerfile
          push: true
          tags: |
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/seqr:latest
            australia-southeast1-docker.pkg.dev/dsp-registry-410602/docker/seqr:${{github.event.workflow_run.head_sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
